# Generated by Django 4.1 on 2022-08-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zepep',
            name='friendship',
            field=models.IntegerField(default=0),
        ),
    ]
